web_admin/card_design/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views.list import CardDesignList
from .views.create import CreateView
from .views.detail import DetailView
from .views.update import UpdateView


app_name = 'card_design'

urlpatterns = [
    url(r'^$', login_required(CardDesignList.as_view(), login_url='authentications:login'), name="card_designs"),
    url(r'^add/$', login_required(CreateView.as_view(), login_url='authentications:login'), name="create_card_design"),
    url(r'^providers/(?P<provider_id>[0-9A-Za-z]+)/details/(?P<card_id>[0-9A-Za-z]+)/$', login_required(DetailView.as_view(), login_url='authentications:login'), name="card_design_detail"),
    url(r'^providers/(?P<provider_id>[0-9A-Za-z]+)/update/(?P<card_id>[0-9A-Za-z]+)/$', login_required(UpdateView.as_view(), login_url='authentications:login'), name="card_design_update"),
]

web_admin/web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.index, name="web-index"),
    url(r'^permission-denied', views.permission_denied, name="permission_denied"),
    url(r'^backlog$', views.backlog, name="backlog"),
]

web_admin/web_admin/urls.py
from django.conf.urls import include, url
from authentications.views.auth import logout_user
from web.views import health
from web.views import backlog

urlpatterns = [
    # url(r'^admin-portal/login/$', auth_views.login, {'template_name': 'authentications/login.html'}, name='login'),
    url(r'^admin-portal/', include('web.urls')),
    url(r'^admin-portal/authentications/', include('authentications.urls')),
    url(r'^admin-portal/clients/', include('clients.urls')),
    url(r'^admin-portal/password-center/', include('password_center.urls')),
    url(r'^admin-portal/balances/', include('balances.urls')),
    url(r'^admin-portal/health$', health, name="health"),
    url(r'^admin-portal/backlog/$', backlog, name="backlog"),
    url(r'^admin-portal/logout/$', logout_user, name='logout'),
    url(r'^admin-portal/agent-type/', include('agent_type.urls')),
    url(r'^admin-portal/system-user/', include('system_user.urls')),
    url(r'^admin-portal/service-group/', include('service_group.urls')),
    url(r'^admin-portal/services/', include('services.urls')),
    url(r'^admin-portal/agents/', include('agents.urls')),
    url(r'^admin-portal/customers/', include('customers.urls')),
    url(r'^admin-portal/cards/', include('cards.urls')),
    url(r'^admin-portal/card-type/', include('card_type.urls')),
    url(r'^admin-portal/cash/', include('cash_sofs.urls')),
    url(r'^admin-portal/payments/', include('payments.urls')),
    url(r'^admin-portal/api-management/', include('api_management.urls')),
    url(r'^admin-portal/centralize-configuration/', include('centralize_configuration.urls')),
    url(r'^admin-portal/bank-sof/', include('bank_sofs.urls')),
    url(r'^admin-portal/bank/', include('bank.urls')),
    url(r'^admin-portal/reconcile/', include('reconcile.urls')),
    url(r'^admin-portal/card-designs/', include('card_design.urls')),
    url(r'^admin-portal/card-provider/', include('card_provider.urls')),
    url(r'^admin-portal/card-sofs/', include('card_sofs.urls')),
    url(r'^admin-portal/balance-adjustment/', include('balance_adjustment.urls')),
    url(r'^admin-portal/campaign/', include('campaign.urls')),
    url(r'^admin-portal/fraud-prevention/', include('fraud_prevention.urls')),
    url(r'^admin-portal/rule-configuration/', include('rule_configuration.urls')),
    url(r'^admin-portal/voucher/', include('voucher.urls')),
    url(r'^admin-portal/report-configuration/', include('report_configuration.urls')),
    url(r'^admin-portal/category/', include('category.urls')),
    url(r'^admin-portal/product/', include('product.urls')),
    url(r'^admin-portal/shop-types/', include('shop_type.urls')),
    url(r'^admin-portal/shop-categories/', include('shop_category.urls')),
    url(r'^admin-portal/shops/', include('shop.urls')),
    url(r'^admin-portal/channel-gateway/services/', include('channel_gateway.service.urls')),
    url(r'^admin-portal/channel-gateway/apis/', include('channel_gateway.api.urls')),
    url(r'^admin-portal/uploads/', include('upload_management.urls')),
    url(r'^admin-portal/otp/', include('authentications.one_time_password_report.urls')),
    url(r'^admin-portal/trust-management/', include('trust_management.urls')),
]

web_admin/agent_type/views/detail.py
from braces.views import GroupRequiredMixin

from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.api_settings import AGENT_TYPE_DETAIL_URL
from web_admin.restful_methods import RESTfulMethods
from web_admin import setup_logger

from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class DetailView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_DELETE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_type_detail.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Agent Type Detail page ==========')
        context = super(DetailView, self).get_context_data(**kwargs)
        agent_type_id = context['agentTypeId']
        params = {"id": agent_type_id}
        data, success = self._post_method(AGENT_TYPE_DETAIL_URL, func_description="", logger=logger, params=params,
                                          only_return_data=True)
        if success:
            context = {
                'agent_type_info': data[0],
                'msg': self.request.session.pop('agent_type_update_msg', None)
            }
        else:
            context = {
                'agent_type_info': {},
                'msg': self.request.session.pop('agent_type_update_msg', None)
            }

        self.logger.info('========== Finished showing Agent Type Detail page ==========')
        return context

web_admin/agents/views/detail.py
from braces.views import GroupRequiredMixin

from web_admin import api_settings, setup_logger
from django.views.generic.base import TemplateView
from web_admin.restful_methods import RESTfulMethods
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from agents.views import AgentAPIService

import logging

logger = logging.getLogger(__name__)
logging.captureWarnings(True)


class DetailView(GroupRequiredMixin, TemplateView, AgentAPIService):
    group_required = "CAN_VIEW_AGENT"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agents/detail.html"
    get_agent_identity_url = api_settings.GET_AGENT_IDENTITY_URL
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Agent Detail page ==========')
        try:
            context = super(DetailView, self).get_context_data(**kwargs)
            agent_id = context['agent_id']

            context, status = self._get_agent_detail(agent_id)
            agent_identity, status_get_agent_identity = self._get_agent_identity(agent_id)
            currencies, status_get_currency = self._get_currencies(agent_id)

            context['msgs'].update({'agent_update_msg': self.request.session.pop('agent_update_msg', None)})

            if status and status_get_agent_identity and status_get_currency:

                agent_type_id = context['agent']['agent_type_id'] if context['agent'][
                                                                         'agent_type_id'] is not None else 0
                agent_type_name, status = self._get_agent_type_name(agent_type_id)

                if status and status_get_agent_identity and status_get_currency:
                    if len(agent_identity['agent_identities']) > 0:
                        context.update({
                            'status_get_agent_identity': agent_identity['agent_identities'][0],
                        })

                    context.update({
                        'agent_type_name': agent_type_name,
                        'currencies': currencies
                    })
                else:
                    context.update({
                        'agent_type_name': context.agent.agent_type_id
                    })

                if context['agent']['mm_card_type_id']:
                    mm_card_type_data, status = self.get_mm_card_type(
                        context['agent']['mm_card_type_id'])
                    if status:
                        context.update({
                            'mm_card_type_name': mm_card_type_data['mm_card_type'][0]['name']
                        })
                    else:
                        context.update({
                            'mm_card_type_name': context['agent']['mm_card_type_id']
                        })

                if context['agent']['mm_card_level_id']:
                    mm_card_type_level, status = self.get_mm_card_type_level(
                        context['agent']['mm_card_level_id'])
                    if status:
                        context.update({
                            'mm_card_type_level_name': mm_card_type_level['mm_card_type_level'][0]['level']
                        })
                    else:
                        context.update({
                            'mm_card_type_level_name': context['agent']['mm_card_level_id']
                        })
                if context['agent']['accreditation']['status_id']:
                    accreditation_status, status = self.get_accreditation_status(
                        context['agent']['accreditation']['status_id'])
                    if status:
                        context.update({
                            'accreditation_status_name': accreditation_status['accreditation_status'][0]['status']
                        })
                    else:
                        context.update({
                            'accreditation_status_name': context['agent']['accreditation']['status_id']
                        })
                if context['agent']['agent_classification_id']:
                    agent_classification_data, status = self.get_agent_classification(
                        context['agent']['agent_classification_id'])
                    if status:
                        context.update({
                            'agent_classification_name': agent_classification_data['agent_classifications'][0]['name']
                        })
                    else:
                        context.update({
                            'agent_classification_name': context.agent.agent_classification_id
                        })
                if context['agent']['referrer_user_type_id']:
                    referrer_agent_type_name, status = self.get_agent_type_name(
                        context['agent']['referrer_user_type_id'])
                    if status:
                        context.update({
                            'referrer_agent_type_name': referrer_agent_type_name
                        })
                    else:
                        context.update({
                            'referrer_agent_type_name': context.agent.referrer_user_type_id
                        })
        except Exception as ex:
            logging.error(ex)
            context = {'agent': {}}
        self.logger.info('========== Finished showing Agent Detail page ==========')
        return context

    def _get_currencies(self, agent_id):
        self.logger.info("================== Start getting currency ==================")
        params = {
            'user_id': agent_id,
            'user_type': 2,
            "paging": False,
            "page_index": -1
        }
        data, success = self._post_method(api_path=api_settings.GET_REPORT_AGENT_BALANCE, params=params)
        self.logger.info("================== Finish getting currency ==================")
        currencies_str = ''
        data = data['cash_sofs']
        if success and data:
            currencies_str = ', '.join([elem["currency"] for elem in data])

        return currencies_str, success

    def _get_agent_detail(self, agent_id):
        body = {'id': agent_id}
        data, success = self._post_method(api_path=api_settings.AGENT_DETAIL_PATH,
                                          func_description="Agent detail",
                                          logger=logger, params=body)
        agents_list = data.get('agents', [])

        context = {
            'agent': agents_list[0],
            'agent_id': agent_id,
            'msgs': {
                'get_msg': self.request.session.pop('agent_registration_msg', None),
                'del_msg': self.request.session.pop('agent_delete_msg', None)
            }
        }
        return context, success

    def _get_agent_identity(self, agent_id):
        self.logger.info("================== Start getting agent identity  ================== ")

        params = {"agent_id": agent_id}
        data, success = self._post_method(api_path=self.get_agent_identity_url, func_description=None, logger=self.logger, params=params, only_return_data=True)

        context = {
            'agent_identities': data
        }
        self.logger.info("================== Finish getting agent identity [{}] agent Id ================== ")
        return context, success

    def _get_agent_type_name(self, agent_type_id):
        self.logger.info("================== Start getting agent type list ==================")
        agent_types_list, success = self._post_method(api_path=api_settings.AGENT_TYPES_LIST_URL,
                                                      func_description="Agent Type List",
                                                      logger=logger)
        self.logger.info("================== Finish getting agent type list ==================")

        if success:
            my_id = int(agent_type_id)
            for x in agent_types_list:
                if x['id'] == my_id:
                    agent_type_name = x['name']
                    return agent_type_name, True
            data = 'Unknown', True
        else:
            data = None, False

        return data

web_admin/bank_sofs/views/detail.py
from web_admin.restful_methods import RESTfulMethods

from django.conf import settings
from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class DetailsView(TemplateView, RESTfulMethods):
    template_name = "bank_sof/detail.html"
    get_bank_sof_detail_url = settings.DOMAIN_NAMES + "api-gateway/report/v1/banks/{id}"

    def get_context_data(self, **kwargs):
        logger.info('========== Start get bank detail ==========')
        context = super(DetailsView, self).get_context_data(**kwargs)
        bank_id = context['bank_id']
        logger.info("Get bank detail with [{}] bank Id".format(bank_id))
        bank = self._get_bank_details(bank_id)
        context = {'bank': bank}
        logger.info('========== Finished get bank detail ==========')
        return context

    def _get_bank_details(self, bank_id):
        data, success = self._get_method(api_path=self.get_bank_sof_detail_url.format(id=bank_id),
                                         func_description="bank detail from backend",
                                         logger=logger,
                                         is_getting_list=True)
        if success:
            return data

web_admin/channel_gateway/api/views/detail.py
from web_admin import api_settings
from django.views.generic.base import TemplateView
from web_admin.get_header_mixins import GetHeaderMixin
from django.shortcuts import render
from channel_gateway.api.utils import get_api_detail
from web_admin.utils import check_permissions, build_logger
from web_admin.restful_helper import RestfulHelper
import logging


logger = logging.getLogger(__name__)

class DetailView(TemplateView, GetHeaderMixin):
    template_name = "channel-gateway-api/detail.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        check_permissions(request, "CAN_VIEW_GW_API")
        self.logger = build_logger(request, __name__)
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        api_id = int(kwargs['id'])
        api = get_api_detail(self, api_id)
        context = {
            "form": api
        }
        return render(request, self.template_name, context)

web_admin/card_design/templates/card_design.html
{% extends "base.html" %}
{% load static %}
{% load permissions_filter %}

{% block content %}
<div class="col-md-12">
    <div class="panel mb25">
        <div class="panel-heading border mb15">
            <h3>Manage Card Design</h3>


        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="col-xs-12">
                <div class="alert alert-success alert-dismissable" id="msg-update-client">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    <strong>{{ message }}</strong>
                </div>
            </div>
            {% endif %}
        {% endfor %}


        <div class="panel-body">
            <form id="submit-form" class="form-horizontal" role="form" method="post" 
            action="{% url 'card_design:card_designs' %}">

            {% csrf_token %}
            
                <div class="col-sm-12  form-group">
                    <label class="col-sm-2">Card Design Name</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control input-rounded" name="card_design_name" 
                        id="txt_card_design_name" value="{{ card_design_name }}"/>
                    </div>

                </div>
                <div class="col-sm-12  form-group">
                    <label class="col-sm-2">Card Type</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control input-rounded" name="card_type" id="ddl_card_type" value="{{ card_type }}">
                    </div>
                </div>
                <div class="col-sm-12  form-group">
                    <label class="col-sm-2">Provider</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control input-rounded" name="provider" id="ddl_provider" value="{{ provider }}">
                    </div>
                </div>
                <div class="col-sm-12  form-group">
                    <label class="col-sm-2">Currency</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control input-rounded" name="currency" id="ddl_currency" value="{{ currency }}">
                    </div>
                     <div class="col-xs-1">
                        <a href="{% url 'card_design:card_designs' %}">
                            <input id="btn_search" class="btn btn-success btn-block" type="submit"  value="Search" name="search">
                        </a>
                    </div>
                </div>
            </form>

            {% if request.user|has_permission_name:"SYS_ADD_CARD_DESIGN"%}
            </div>
                <div class="pull-right mr15 text-right">
                <a href="{% url 'card_design:create_card_design' %}">
                    <input id="btn_add" class="btn btn-success btn-block btn-sm mb15" type="button"
                           value="Add"/>
                </a>
            </div>
            {% endif %}
            <div class="no-more-tables">
                <table id='tbl_card_design' class="table table-bordered table-striped mb0">
                    <thead>
                    <tr>
                        <th id="ddl_card_design_number">Card Design Number</th>
                        <th id="ddl_card_design_name">Card Design Name</th>
                        <th id="ddl_provider">Provider</th>
                        <th id="ddl_card_type">Card Type</th>
                        <th id="ddl_currency">Currency</th>
                        <th class="col-sm-2" id="action">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if request.user|has_permission_name:"SYS_VIEW_LIST_CARD_DESIGN"%}
                    {% for i in data %}
                        <tr>
                            <td>{{ i.pan_pattern|default_if_none:'' }}</td>
                            <td>{{ i.name|default_if_none:'' }}</td>
                            <td>{{ i.provider.name|default_if_none:'' }}</td>
                            <td>{{ i.card_type.name|default_if_none:'' }}</td>
                            <td>{{ i.currency|default_if_none:'' }}</td>
                            <td class="col-sm-2">
                                {% if i.is_permission_edit%}
                                <a type="button"
                                    class="btn btn-outline btn-xs btn-primary"
                                    role="button"
                                    id="btn_edit">
                                    <span class="small">Edit</span>
                                </a>
                                {%endif%}
                                {% if i.is_permission_edit%}
                                <a type="button"
                                    class="btn btn-outline btn-xs btn-info"
                                    role="button"
                                    id="btn_detail"
                                    href="{% url 'card_design:card_design_detail' i.id i.provider.id %}">
                                    <span class="small">Detail</span>
                                </a>
                                {%endif%}
                            </td>
                        </tr>
                    {% endfor %}
                    {%endif%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}