web_admin/reconcile/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url

from .views.partner_report import PartnerReport
from .views.sof_report import SofReport
from .views.partner_file_list import PartnerFileList
from .views.sof_file_list import SofFileList
from .views.service_list import ServiceList

app_name = 'reconcile'

urlpatterns = [
    url(r'^partner/file-list/$', login_required(PartnerFileList.as_view(),
                                                login_url='authentications:login'), name="reconcile_partner_file_list"),
    url(r'^partner/report/$', login_required(PartnerReport.as_view(),
                                                login_url='authentications:login'), name="reconcile_partner_report"),
    url(r'^partner/report/(?P<partner_file_id>[0-9A-Za-z]+)/$', login_required(PartnerReport.as_view(),
                                                login_url='authentications:login'), name="reconcile_partner_report_by_file_id"),
    url(r'^sof/file-list/$', login_required(SofFileList.as_view(),
                                                login_url='authentications:login'), name="reconcile_sof_file_list"),
    url(r'^sof/report/$', login_required(SofReport.as_view(),
                                                login_url='authentications:login'), name="reconcile_sof_report"),
    url(r'^sof/report/(?P<sofFileId>[0-9A-Za-z]+)/$', login_required(SofReport.as_view(),
                                                login_url='authentications:login'), name="reconcile_sof_report_by_file_id"),
    url(r'^service/list/$', login_required(ServiceList.as_view(),
                                         login_url='authentications:login'), name="reconcile_service_list")
]

web_admin/web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.index, name="web-index"),
    url(r'^permission-denied', views.permission_denied, name="permission_denied"),
    url(r'^backlog$', views.backlog, name="backlog"),
]

web_admin/web_admin/urls.py
from django.conf.urls import include, url
from authentications.views.auth import logout_user
from web.views import health
from web.views import backlog

urlpatterns = [
    # url(r'^admin-portal/login/$', auth_views.login, {'template_name': 'authentications/login.html'}, name='login'),
    url(r'^admin-portal/', include('web.urls')),
    url(r'^admin-portal/authentications/', include('authentications.urls')),
    url(r'^admin-portal/clients/', include('clients.urls')),
    url(r'^admin-portal/password-center/', include('password_center.urls')),
    url(r'^admin-portal/balances/', include('balances.urls')),
    url(r'^admin-portal/health$', health, name="health"),
    url(r'^admin-portal/backlog/$', backlog, name="backlog"),
    url(r'^admin-portal/logout/$', logout_user, name='logout'),
    url(r'^admin-portal/agent-type/', include('agent_type.urls')),
    url(r'^admin-portal/system-user/', include('system_user.urls')),
    url(r'^admin-portal/service-group/', include('service_group.urls')),
    url(r'^admin-portal/services/', include('services.urls')),
    url(r'^admin-portal/agents/', include('agents.urls')),
    url(r'^admin-portal/customers/', include('customers.urls')),
    url(r'^admin-portal/cards/', include('cards.urls')),
    url(r'^admin-portal/card-type/', include('card_type.urls')),
    url(r'^admin-portal/cash/', include('cash_sofs.urls')),
    url(r'^admin-portal/payments/', include('payments.urls')),
    url(r'^admin-portal/api-management/', include('api_management.urls')),
    url(r'^admin-portal/centralize-configuration/', include('centralize_configuration.urls')),
    url(r'^admin-portal/bank-sof/', include('bank_sofs.urls')),
    url(r'^admin-portal/bank/', include('bank.urls')),
    url(r'^admin-portal/reconcile/', include('reconcile.urls')),
    url(r'^admin-portal/card-designs/', include('card_design.urls')),
    url(r'^admin-portal/card-provider/', include('card_provider.urls')),
    url(r'^admin-portal/card-sofs/', include('card_sofs.urls')),
    url(r'^admin-portal/balance-adjustment/', include('balance_adjustment.urls')),
    url(r'^admin-portal/campaign/', include('campaign.urls')),
    url(r'^admin-portal/fraud-prevention/', include('fraud_prevention.urls')),
    url(r'^admin-portal/rule-configuration/', include('rule_configuration.urls')),
    url(r'^admin-portal/voucher/', include('voucher.urls')),
    url(r'^admin-portal/report-configuration/', include('report_configuration.urls')),
    url(r'^admin-portal/category/', include('category.urls')),
    url(r'^admin-portal/product/', include('product.urls')),
    url(r'^admin-portal/shop-types/', include('shop_type.urls')),
    url(r'^admin-portal/shop-categories/', include('shop_category.urls')),
    url(r'^admin-portal/shops/', include('shop.urls')),
    url(r'^admin-portal/channel-gateway/services/', include('channel_gateway.service.urls')),
    url(r'^admin-portal/channel-gateway/apis/', include('channel_gateway.api.urls')),
    url(r'^admin-portal/uploads/', include('upload_management.urls')),
    url(r'^admin-portal/otp/', include('authentications.one_time_password_report.urls')),
    url(r'^admin-portal/trust-management/', include('trust_management.urls')),
]

web_admin/reconcile/views/partner_file_list.py
import logging
import requests

from braces.views import GroupRequiredMixin
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from django.shortcuts import render
from django.views.generic.base import TemplateView
from web_admin import api_settings
from multiprocessing.pool import ThreadPool
from web_admin.restful_methods_reconcile import RESTfulReconcileMethods
from web_admin.utils import setup_logger
from datetime import datetime, timedelta
from web_admin.utils import calculate_page_range_from_page_info

logger = logging.getLogger(__name__)

IS_SUCCESS = {
    True: 'Success',
    False: 'Failed',
}


class PartnerFileList(GroupRequiredMixin, TemplateView, RESTfulReconcileMethods):
    template_name = "reconcile/partner_file_list.html"
    logger = logger

    group_required = "CAN_GET_FILE_LIST_PARTNER_RECONCILE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(PartnerFileList, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):

        # Set first load default time for Context
        default_end_date = datetime.today().strftime("%Y-%m-%d")
        default_start_date = (datetime.today() - timedelta(days=1)).strftime("%Y-%m-%d")

        context = {'from_created_timestamp': default_start_date,
                   'to_created_timestamp': default_end_date }

        currencies, success = self._get_currency_choices()
        if success:
            context.update({'currencies': currencies})

        services_list, service_groups, service_group_id, success = self._get_service_group_and_services_list(-1)
        if success:
            context.update({'service_list': services_list,
                            'service_groups': service_groups,
                            'service_group_id': service_group_id})
        else:
            context.update({'partner_file_list_error_msg': 'Fail to get service group, please refresh the page or contact technical support'})

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        self.logger.info('========== Start searching partner file list ==========')
        context = super(PartnerFileList, self).get_context_data(**kwargs)

        opening_page_index = request.POST.get('current_page_index')
        is_on_us = request.POST.get('on_off_us_id')
        service_group_id = request.POST.get('service_group_id')
        service_name = request.POST.get('service_name')
        agent_id = request.POST.get('partner_id')
        currency = request.POST.get('currency_id')
        reconcile_status = request.POST.get('reconcile_status_id')
        from_created_timestamp = request.POST.get('from_created_timestamp')
        to_created_timestamp = request.POST.get('to_created_timestamp')

        params = {}
        params['opening_page_index'] = opening_page_index

        is_on_us_id = int(is_on_us)
        reconcile_status_id = int(reconcile_status)

        if is_on_us_id >= 0:
            params['is_on_us'] = (is_on_us_id == 1)

        if service_name != '':
            if service_name == None:
                params['service_name'] = ''
            else:
                params['service_name'] = service_name

        if agent_id != '':
            params['agent_id'] = int(agent_id)

        if currency != '':
            params['currency'] = currency

        if reconcile_status_id >= 0:
            params['status_id'] = reconcile_status_id

        if from_created_timestamp is not '':
            new_from_created_timestamp = datetime.strptime(from_created_timestamp, "%Y-%m-%d")
            new_from_created_timestamp = new_from_created_timestamp.strftime('%Y-%m-%dT%H:%M:%SZ')
            params['from_last_updated_timestamp'] = new_from_created_timestamp

        if to_created_timestamp is not '':
            new_to_created_timestamp = datetime.strptime(to_created_timestamp, "%Y-%m-%d")
            new_to_created_timestamp = new_to_created_timestamp.replace(hour=23, minute=59, second=59)
            new_to_created_timestamp = new_to_created_timestamp.strftime('%Y-%m-%dT%H:%M:%SZ')
            params['to_last_updated_timestamp'] = new_to_created_timestamp

        currencies, success = self._get_currency_choices()
        if success is True:
            context.update({'currencies': currencies})

        services_list, service_groups, service_group_id, success = self._get_service_group_and_services_list(
            service_group_id)
        if success is True:
            context.update({'service_list': services_list,
                            'service_groups': service_groups,
                            'service_group_id': service_group_id})
        else:
            context.update({'partner_file_list_error_msg': 'Fail to get service group, please refresh the page or contact technical support'})
            params.pop('service_name','')

        try:
            data, page, status_code = self._search_file_list(params)
            if status_code == 500:
                self.logger.error('Search fail, please try again or contact technical support')
                context.update({'partner_file_list_error_msg': 'Search fail, please try again or contact technical support'})
            else:
                context.update({'file_list': data, 'paginator': page, 'page_range': calculate_page_range_from_page_info(page)})

        except requests.Timeout:
            self.logger.error('Search partner file list request timeout')
            context.update({'partner_file_list_error_msg': 'Search timeout, please try again or contact technical support'})

        context.update({'is_on_us': is_on_us_id,
                        'agent_id': agent_id,
                        'currency': currency,
                        'status_id': reconcile_status_id,
                        'from_created_timestamp': from_created_timestamp,
                        'to_created_timestamp': to_created_timestamp,
                        'selected_service': service_name})

        self.logger.info("========== Finish searching partner file list ==========")

        return render(request, self.template_name, context)

    def _search_file_list(self, params):
        self.logger.info('========== Start Searching Partner File List ==========')
        api_path = api_settings.SEARCH_RECONCILE_PARTNER_FILE_LIST
        response_json, success = self._post_method(
            api_path=api_path,
            func_description="Search Partner File List",
            logger=logger,
            params=params,
            only_return_data=False
        )
        self.logger.info("data={}".format(response_json.get('data')))
        self.logger.info('========== Finish Searching Partner File List ==========')
        return response_json.get('data'), response_json.get('page'), response_json.get("status_code")

    def _get_currency_choices(self):
        self.logger.info('========== Start Getting Currency Choices ==========')
        url = api_settings.GET_ALL_CURRENCY_URL
        data, success = self._get_method(url, "currency choice", logger)

        if success:
            value = data.get('value', '')
            if isinstance(value, str):
                currency_list = map(lambda x: x.split('|'), value.split(','))
            else:
                currency_list = []
            result = currency_list, True
        else:
            result = [], False
        self.logger.info('========== Finish Getting Currency Choices ==========')
        return result

    def _get_service_group_choices(self):
        self.logger.info('========== Start Getting Service Groups ==========')
        url = api_settings.SERVICE_GROUP_LIST_URL
        service_group_list = self._get_method(url, "services group list", logger, True)
        self.logger.info('========== Finish Getting Service Groups ==========')
        return service_group_list

    def _get_service_group_and_currency_choices(self):
        self.logger.info('========== Start Getting Service_Groups and Currencies Choices ==========')
        pool = ThreadPool(processes=1)
        async_result = pool.apply_async(self._get_currency_choices)
        self.logger.info('========== Start Getting Service Group Choices ==========')
        service_groups, success_service = self._get_service_group_choices()
        self.logger.info('========== Finish Getting Service Group Choices ==========')
        currencies, success_currency = async_result.get()
        if success_currency and success_service:
            return {
                       'currencies': currencies,
                       'service_groups': service_groups,
                   }, True
        self.logger.info('========== Finish Getting Service_Groups and Currencies Choices ==========')
        return None, False

    def _get_service(self, service_group_id):
        self.logger.info('========== Start Getting Service List ==========')
        if service_group_id == -1:
            data, success = self._get_method(api_settings.GET_ALL_SERVICE_URL, "Get all service", logger)
        else:
            data, success = self._get_method(
                api_settings.GET_SERVICE_BY_SERVICE_GROUP_URL.format(service_group_id=service_group_id),
                "Get services by service group",
                logger)
        self.logger.info('========== Finish Getting Service List ==========')
        return data, success

    def _get_service_group_and_services_list(self, service_group_id):

web_admin/reconcile/views/service_list.py
import json
import logging

from django.http import HttpResponse
from django.views.generic.base import TemplateView

from web_admin import api_settings, setup_logger
from web_admin.restful_methods_reconcile import RESTfulReconcileMethods
from authentications.utils import get_correlation_id_from_username

logger = logging.getLogger(__name__)

class ServiceList(TemplateView, RESTfulReconcileMethods):

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(ServiceList, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        service_group_id = request.GET.get('service_group_id')
        services_list = self._get_service(service_group_id)
        data = json.dumps(services_list)
        return HttpResponse(data, content_type='application/json')

    def _get_service(self, service_group_id):
        self.logger.info('========== Start Getting Services List ==========')
        if service_group_id == '-1':
            url = api_settings.GET_ALL_SERVICE_URL
        else:
            url = api_settings.GET_SERVICE_URL.format(serviceGroupId=service_group_id)
        service_list = self._get_method(url, "Get services list", logger, True)
        status = service_list[1]
        if status is not True:
            logger.error("Get Services List Error")
        self.logger.info('========== Finish Getting Services List ==========')
        return service_list

web_admin/reconcile/templates/reconcile/partner_file_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="panel mb25">
    <div class="panel-heading border">
        <h3>Partner File List</h3>
    </div>

    <div class="panel-body">
        {% if partner_file_list_error_msg is not None %}
        <div class="col-xs-12">
            <div class='alert alert-danger alert-dismissable' id="msg-update-client">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ partner_file_list_error_msg }}</strong>
            </div>
        </div>
        {% endif %}
        <form id="submit-form" class="form-horizontal" role="form" method="post"
              action="{% url 'reconcile:reconcile_partner_file_list' %}">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">On us/Off us</label>
                <div class="col-xs-2">
                    <select class="form-control" id="ddl_on_off_us" name="on_off_us_id">
                        <option value=-1 {% if is_on_us == -1 %}selected="selected"{% endif %}>All</option>
                        <option value=1 {% if is_on_us == 1 %}selected="selected"{% endif %}>On</option>
                        <option value=0 {% if is_on_us == 0 %}selected="selected"{% endif %}>Off</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Service Group</label>
                <div class="col-xs-2">
                    <select class="form-control" id="ddl_service_group" name="service_group_id"
                            onchange="ddl_service_group_change()">
                     {% if service_groups is not None %}
                        <option value=-1>All</option>
                        {% for group in service_groups %}
                            <option value={{ group.service_group_id }}
                                            {% if service_group_id == group.service_group_id %}selected="selected"{% endif %}>{{ group.service_group_name }}</option>
                        {% endfor %}
                    {% endif %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Service</label>
                <div class="col-xs-2">
                    <select class="form-control" id="ddl_service" name="service_name">
                    {% if service_list is not None %}
                        {% if service_group_id == -1 %}<option value=''>All</option>{% endif %}
                        {% for service_in in service_list %}
                            <option value='{{ service_in.service_name }}'
                                            {% if service_in.service_name == selected_service %}selected="selected"{% endif %}>{{ service_in.service_name }}</option>
                        {% endfor %}
                    {% endif %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Partner ID (Agent ID)</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control input-rounded" name="partner_id" id="partner_id"
                           value="{{ agent_id|default_if_none:'' }}" style="text-align:right;"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Currency</label>
                <div class="col-xs-2">
                    <select class="form-control" id="ddl_currency" name="currency_id">
                        <option value="">All</option>
                        {% for choice_currency in currencies %}
                            <option value="{{ choice_currency.0 }}"
                                    {% if choice_currency.0 == currency %}selected="selected"{% endif %}>
                                {{ choice_currency.0 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Reconcile status</label>
                <div class="col-xs-2">
                    <select class="form-control" id="ddl_reconcile_status" name="reconcile_status_id">
                        <option value=-1 {% if status_id == -1 %}selected="selected"{% endif %}>All</option>
                        <option value=4 {% if status_id == 4 %}selected="selected"{% endif %}>Reconciled</option>
                        <option value=5 {% if status_id == 5 %}selected="selected"{% endif %}>Unreconciled</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Start date</label>
                <div class="col-sm-2">
                    <input type="date" class="form-control input-rounded"
                           name="from_created_timestamp"
                           value="{{ from_created_timestamp|default_if_none:'' }}"
                           id="dtp_from">
                </div>
                <label class="col-sm-1 control-label">End date</label>
                <div class="col-sm-2">
                    <input type="date" class="form-control input-rounded"
                           name="to_created_timestamp"
                           value="{{ to_created_timestamp|default_if_none:'' }}"
                           id="dtp_to">
                </div>
            </div>
            <input id="current_page_index" name="current_page_index" style="display:none" value="1">
            <div class="form-group">
                <div class="pull-right col-sm-1">
                    <button id="btn_search" class="btn btn-success text-left mb15" type="submit">Search</button>
                </div>
            </div>
        </form>
        {% if paginator %}
        <label class="col-sm-12" style="text-align:right"><b>(Total {{ paginator.total_elements }})</b></label>
        {% endif %}
        <div class="table-responsive">
            <table class="table table-bordered table-striped mb0" id="tbl_file_list">
                <thead>
                <tr>
                    <th id="id_clm">ID</th>
                    <th id="file_name_clm">File Name</th>
                    <th id="is_us_on_clm">ON US/OFF US</th>
                    <th id="service_clm">Service</th>
                    <th id="partner_id_clm">Partner ID</th>
                    <th id="currency_clm">Currency</th>
                    <th id="processing_status_clm">Status</th>
                    <th id="reconcile_date_clm">Reconcile Date</th>
                    <th id="action_clm">Action</th>
                </tr>
                </thead>
                <tbody id="table_body">
                {% for file in file_list %}
                    <tr>
                        <td class="col-sm-2">{{ file.id|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ file.file_name|default_if_none:'' }}</td>
                        <td class="col-sm-2">{% if file.is_on_us is True %} ON US {% elif file.is_on_us is False %} OFF US {% endif %}</td>
                        <td class="col-sm-2">{{ file.service_name|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ file.agent_id|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ file.currency|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ file.status.name|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ file.last_updated_timestamp|default_if_none:'' }}</td>
                        <td class="col-sm-3">
                            {% if file.status.id is 4 or file.status.id is 5 %}
                                <div class="btn-group">
                                    <button class="btn btn-outline btn-xs btn-primary"
                                            onclick="redirectToReportPage('{{ file.is_on_us }}',
                                                    '{{ file.service_name }}', '{{ file.agent_id }}',
                                                    '{{ file.currency }}', '{{ file.last_updated_timestamp}}',
                                                    '{{ file.last_updated_timestamp}}',
                                                    '{% url 'reconcile:reconcile_partner_report_by_file_id' file.id %}')">
                                        <u>Result</u>
                                    </button>
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "pagination.html" %}
    </div>
</div>
{% endblock %}
{% block body_js %}
{{ block.super }}
    <script type="text/javascript">
    ddl_service_group_change = function () {
        console.log("{% url 'reconcile:reconcile_service_list' %}")
        serv_gr_id = $("#ddl_service_group").val()
        console.log(serv_gr_id)
        $.ajax({
            type: "GET",
            url: "{% url 'reconcile:reconcile_service_list' %}",
            data: {'service_group_id': serv_gr_id},
            success: function (response) {
                console.log(response.toString())
                var success = response[1]
                if (success == true) {
                    var options = {};
                    for (var i = 0; i < response[0].length; i++) {
                        options[response[0][i]['service_id']] = response[0][i]['service_name']
                    }
                    add_option('#ddl_service', options)
                } else {
                    console.log("Error get service")
                    on_get_services_error()
                }
            },
            error: function (xhr) {
                console.log("Error get service")
                on_get_services_error()
            }
        });
    }

    on_get_services_error = function () {
        $('#ddl_service').empty()
        $('#ddl_service_group').empty()
        var error_alert = $("<div class='col-xs-12'></div>").append(
            $("<div class='alert alert-danger alert-dismissable' id='msg-update-client'></div>").append(
                "<a href='#' class='close' data-dismiss='alert' aria-label='close'>×</a>").append(
                "<strong>Fail to get service group, please refresh the page or contact technical support</strong>"
            )
        );
        var _panel_heading = document.getElementsByClassName('panel-heading border')
        error_alert.insertAfter(_panel_heading)
    }

    add_option = function (ddlId, dict) {
        var _select = $(ddlId);
        _select.empty()
        if ($("#ddl_service_group").val() == -1) {
            _select.append(
                $('<option></option>').val('').html('All')
            );
        }

        $.each(dict, function (val, text) {
            _option = $('<option></option>').val(text).html(text)
            _select.append(_option);
        });
    }

    function composeInput(name, value) {
        return jQuery('<input>', {'name': name, 'value': value});
    }

    function convertDate(dateString) {
        var aDate = new Date(dateString);
        var year = aDate.getFullYear();
        var month = aDate.getMonth() + 1;
        var date = aDate.getDate();
        if (month < 10) {
            month = '0' + month;
        }
        if (date < 10) {
            date = '0' + date;
        }
        return year + '-' + month + '-' + date;
    }

    function redirectToReportPage(isOnUS, serviceName, agentId, currency, startDate, endDate, report_url) {
        var newForm = jQuery('<form>', {
            'action': report_url,
            'method': 'post'
        });

        newForm.append(composeInput('csrfmiddlewaretoken', $("[name='csrfmiddlewaretoken']").val()));
        newForm.append(composeInput('current_page_index', 1));
        newForm.append(composeInput('on_off_us_id', isOnUS === "True" ? 1 : 0));
        newForm.append(composeInput('service_group_id', -1));
        newForm.append(composeInput('service_id', serviceName));
        newForm.append(composeInput('partner_id', agentId));
        newForm.append(composeInput('currency_id', currency));
        newForm.append(composeInput('reconcile_status_id', -1));
        newForm.append(composeInput('reconcile_payment_type_id', -1));
        newForm.append(composeInput('from_created_timestamp', convertDate(startDate)));
        newForm.append(composeInput('to_created_timestamp', convertDate(endDate)));

        $(document.body).append(newForm);
        newForm.submit();
    }
</script>
{%  endblock %}