web_admin/bank/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from bank.views.bank.create import CreateView
from bank.views.bank.delete import DeleteView
from bank.views.bank.edit import EditView
from bank.views.bank.list import ListView
from bank.views.bank.detail import DetailsView


app_name = 'bank'

urlpatterns = [
    url(r'^management/$', login_required(ListView.as_view(), login_url='authentications:login'), name="bank_sofs_list"),
    url(r'^sofs/create/$', login_required(CreateView.as_view(), login_url='authentications:login'), name="bank_sofs_create"),
    url(r'^sofs/(?P<bank_id>[0-9A-Za-z]+)/edit/$', login_required(EditView.as_view(), login_url='authentications:login'), name="bank_sofs_edit"),
    url(r'^sofs/(?P<bank_id>[0-9A-Za-z]+)/detail/$', login_required(DetailsView.as_view(), login_url='authentications:login'), name="bank_sofs_detail"),
    url(r'^sofs/(?P<bank_id>[0-9A-Za-z]+)/delete/$', login_required(DeleteView.as_view(), login_url='authentications:login'), name="bank_sofs_delete"),
]

web_admin/cards/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from .views.profile import ProfileView
from .views.history import HistoryView
from .views.card_freeze_list import CardFreezeList
from .views.active import active
from .views.deactive import deactive

app_name = 'cards'

urlpatterns = [
    url(r'^profile/$', login_required(ProfileView.as_view(), login_url='authentications:login'), name="profile"),
    url(r'^history/$', login_required(HistoryView.as_view(), login_url='authentications:login'), name="history"),
    url(r'^card-freeze-list/$', login_required(CardFreezeList.as_view(), login_url='authentications:login'),
        name="card_freeze_list"),
    url(r'^card-freeze-list/delete/(?P<id>[^/]+)/$', login_required(CardFreezeList.as_view(), login_url='authentications:login'),
        name="delete_card_freeze"),
    url(r'^profile-card/(?P<id>[0-9A-Za-z]+)/activate/$', login_required(active, login_url='authentications:login'),
        name="activate_profile_card"),
    url(r'^profile-card/(?P<id>[0-9A-Za-z]+)/deactivate/$', login_required(deactive, login_url='authentications:login'),
        name="deactivate_profile_card"),
]

web_admin/payments/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url

from .views.payment_order_list import PaymentOrderView
from .views.order_detail import OrderDetailView
from .views.user_list import UserList

app_name = 'payments'

urlpatterns = [
    url(r'^orders/$', login_required(PaymentOrderView.as_view(), login_url='authentications:login'), name="payment_order"),
    url(r'^orders/(?P<order_id>[0-9A-Za-z]+)/details$', login_required(OrderDetailView.as_view(), login_url='authentications:login'), name="order_detail"),
    url(r'^users/$', login_required(UserList.as_view(), login_url='authentications:login'),
        name="search_user")

]

web_admin/shop/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url

from shop.views.ajax import Agent_Detail
from .views.create import CreateView
from .views.delete import DeleteView
from .views.detail import DetailView
from .views.edit import EditView
from .views.list import ListView
from .views.device_update import DeviceUpdateView
from .views.add_device import AddDeviceView
from .views.device_management_ajax import grant_channel_access, revoke_channel_access, enable_device, disable_device, unbind_device

app_name = 'shop'

urlpatterns = [
url(r'^ajax/agent-detail/(?P<id>[0-9A-Za-z]+)/$', login_required(Agent_Detail.as_view(), login_url='authentications:login'), name="ajax_agent_detail"),
    url(r'^$', login_required(ListView.as_view(), login_url='authentications:login'), name="shop_list"),
    url(r'^create/$', login_required(CreateView.as_view(), login_url='authentications:login'), name="shop_create"),
    url(r'^(?P<id>[0-9A-Za-z]+)/edit/$', login_required(EditView.as_view(), login_url='authentications:login'), name="shop_edit"),
    url(r'^(?P<id>[0-9A-Za-z]+)/detail/$', login_required(DetailView.as_view(), login_url='authentications:login'), name="shop_detail"),
    url(r'^(?P<id>[0-9A-Za-z]+)/delete/$', login_required(DeleteView.as_view(), login_url='authentications:login'), name="shop_delete"),
    url(r'^(?P<id>[0-9A-Za-z]+)/devices/(?P<device_id>[0-9A-Za-z]+)/edit', login_required(DeviceUpdateView.as_view(), login_url='authentications:login'), name="device_update"),
    url(r'^(?P<agent_id>[0-9A-Za-z]+)/(?P<shop_id>[0-9A-Za-z]+)/channels/(?P<channel_id>[0-9A-Za-z]+)/grant$', login_required(grant_channel_access, login_url='authentications:login'), name="grant_channel_access"),
    url(r'^(?P<agent_id>[0-9A-Za-z]+)/(?P<shop_id>[0-9A-Za-z]+)/channels/(?P<channel_id>[0-9A-Za-z]+)/revoke$', login_required(revoke_channel_access, login_url='authentications:login'), name="revoke_channel_access"),
    url(r'^devices/(?P<device_id>[0-9A-Za-z]+)/enable$', login_required(enable_device, login_url='authentications:login'), name="enable_device"),
    url(r'^devices/(?P<device_id>[0-9A-Za-z]+)/disable$', login_required(disable_device, login_url='authentications:login'), name="disable_device"),
    url(r'^devices/(?P<device_id>[0-9A-Za-z]+)/unbind$', login_required(unbind_device, login_url='authentications:login'), name="unbind_device"),
    url(r'^(?P<shop_id>[0-9A-Za-z]+)/devices$', login_required(AddDeviceView.as_view(), login_url='authentications:login'), name="add_device"),
]

web_admin/upload/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views.upload import Upload
from .views.download import Download



app_name = 'upload'

urlpatterns = [
    url(r'^$', login_required(Upload.as_view(), login_url='authentications:login'), name="upload"),
    url(r'^download$', login_required(Download.as_view(), login_url='authentications:login'), name="download"),

]

web_admin/web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.index, name="web-index"),
    url(r'^permission-denied', views.permission_denied, name="permission_denied"),
    url(r'^backlog$', views.backlog, name="backlog"),
]

web_admin/authentications/one_time_password_report/models.py
from django.db import models

# Create your models here.

web_admin/card_type/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

web_admin/agent_type/views/create.py
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.restful_methods import RESTfulMethods
from web_admin.api_settings import AGENT_TYPE_CREATE_URL
from web_admin import setup_logger

from braces.views import GroupRequiredMixin

from django.conf import settings
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class AgentTypeCreate(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_CREATE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/create_agent_type.html"
    logger = logger

    permission_required = "auth.change_user"
    login_url = settings.LOGIN_URL
    raise_exception = False

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(AgentTypeCreate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Create Agent Type page ==========')
        context = super(AgentTypeCreate, self).get_context_data(**kwargs)
        self.logger.info('========== Finished showing Create Agent Type page ==========')
        return context

    def post(self, request, *args, **kwargs):
        self.logger.info('========== Start creating agent type ==========')
        params = {
            "name": request.POST.get('agent_type_input'),
            "description": request.POST.get('agent_type_description_input'),
        }

        data, success = self._post_method(api_path=AGENT_TYPE_CREATE_URL,
                                          func_description="Agent Type",
                                          logger=logger, params=params)
        if success:
            request.session['agent_type_create_msg'] = 'Added data successfully'
            self.logger.info('========== Finished creating agent type ==========')
            return redirect('agent_type:agent-type-list')
        else:
            context = {
                'agent_type_info': params,
                'error_msg': data
            }
            self.logger.info('========== Finished creating agent type ==========')
            return render(request, 'agent_type/create_agent_type.html', context)

web_admin/agent_type/views/delete.py
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.restful_methods import RESTfulMethods
from web_admin.api_settings import AGENT_TYPE_DETAIL_URL, DELETE_AGENT_TYPE_URL
from web_admin import setup_logger
from django.shortcuts import render
from braces.views import GroupRequiredMixin

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
import logging

logger = logging.getLogger(__name__)


class DeleteView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_DELETE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_type_delete.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(DeleteView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Delete Agent Type page ==========')
        try:
            context = super(DeleteView, self).get_context_data(**kwargs)
            agent_type_id = context['agent_type_id']  
            self.logger.info('========== Finished showing Delete Agent Type page ==========')          
            return self._get_agent_type_detail(agent_type_id)
        except Exception as e:
            self.logger.error(e)
            context = {}
            self.logger.info('========== Finished showing Delete Agent Type page ==========')
            return context

    def post(self, request, *args, **kwargs):
        self.logger.info('========== Start deleting agent type ==========')
        agent_type_id = kwargs['agent_type_id']

        data, success = self._delete_method(api_path=DELETE_AGENT_TYPE_URL.format(agent_type_id),
                                            func_description="Delete agent type",
                                            logger=logger)
        if success:
            request.session['agent_type_delete_msg'] = 'Deleted data successfully'
            self.logger.info('========== Finished deleting agent type ==========')
            return HttpResponseRedirect(reverse('agent_type:agent-type-list'))
        else:
            context = self._get_agent_type_detail(agent_type_id)
            self.logger.info('========== Finished deleting agent type ==========')
            context.update({
                'msg':data,
            })
            return render(request, self.template_name, context)
        return success

    def _get_agent_type_detail(self, agent_type_id):
        param = {'id': agent_type_id}
        data, success = self._post_method(api_path=AGENT_TYPE_DETAIL_URL,
                                         func_description="Agent Type",
                                         logger=logger,
                                         params = param)
        return {'agent_type_info': data[0]}

web_admin/agent_type/views/detail.py
from braces.views import GroupRequiredMixin

from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.api_settings import AGENT_TYPE_DETAIL_URL
from web_admin.restful_methods import RESTfulMethods
from web_admin import setup_logger

from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class DetailView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_DELETE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_type_detail.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Agent Type Detail page ==========')
        context = super(DetailView, self).get_context_data(**kwargs)
        agent_type_id = context['agentTypeId']
        params = {"id": agent_type_id}
        data, success = self._post_method(AGENT_TYPE_DETAIL_URL, func_description="", logger=logger, params=params,
                                          only_return_data=True)
        if success:
            context = {
                'agent_type_info': data[0],
                'msg': self.request.session.pop('agent_type_update_msg', None)
            }
        else:
            context = {
                'agent_type_info': {},
                'msg': self.request.session.pop('agent_type_update_msg', None)
            }

        self.logger.info('========== Finished showing Agent Type Detail page ==========')
        return context

web_admin/agent_type/views/list.py
from braces.views import GroupRequiredMixin

from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.api_settings import AGENT_TYPES_LIST_URL
from web_admin.restful_methods import RESTfulMethods
from web_admin import setup_logger

from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class ListView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_MANAGE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_types_list.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(ListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Agent Type List page ==========')
        data = self.get_agent_types_list()
        result = {
            'data': data,
            'msgs': {
                'del_msg': self.request.session.pop('agent_type_delete_msg', None),
                'cre_msg': self.request.session.pop('agent_type_create_msg', None)
            }
        }
        self.logger.info('========== Finished showing Agent Type List page ==========')
        return result

    def get_agent_types_list(self):
        data, success = self._post_method(api_path=AGENT_TYPES_LIST_URL,
                                         func_description="Agent Type List",
                                         logger=logger)
        return data

web_admin/agents/views/activate.py
import logging
from django.conf import settings
from web_admin import api_settings, setup_logger
from web_admin import ajax_functions
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user


def activate(request, agent_id):
    logger = logging.getLogger(__name__)
    correlation_id = get_correlation_id_from_username(request.user)
    logger = setup_logger(request, logger, correlation_id)
    logger.info("Checking permission for [{}] username with [{}] permission".format(request.user, 'CAN_SUSPEND_AGENTS'))
    if not check_permissions_by_user(request.user, 'CAN_SUSPEND_AGENTS'):
        return {"status": 1, "msg": ''}
    logger.info('========== Start activating agent ==========')
    url = settings.DOMAIN_NAMES + api_settings.AGENT_STATUS_URL.format(agent_id)
    params = {
        'is_suspended': False,
    }

    result = ajax_functions._put_method(request, url, "", logger, params)
    logger.info('========== Finish activating agent ==========')
    return result

web_admin/templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title>Operation Web</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    {% block body_stylesheet %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/sweetalert/lib/sweet-alert.css' %}">
    <link rel="stylesheet" href="{% static 'styles/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'styles/urban.css' %}">
    <link rel="stylesheet" href="{% static 'styles/urban.skins.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}?{% now "U" %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}?{% now "U" %}">
    {% endblock %}
</head>
<body style="background-color: white;">
{% block body_content %}
<div class="app layout-fixed-header">

    <!--sidebar-panel-->
    {% include 'navigation.html' %}

    <!-- content panel -->
    <div class="main-panel">
        <!-- top header -->
        <header class="header navbar">

            <div class="brand visible-xs">
                <!-- toggle offscreen menu -->
                <div class="toggle-offscreen">
                    <a href="#" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <!-- /toggle offscreen menu -->
                <!-- logo -->
                <div class="brand-logo">
                    <!--<img src="images/logo-dark.png" height="15" alt="">-->
                </div>
                <!-- /logo -->
                <!-- toggle chat sidebar small screen-->
                <div class="toggle-chat">
                    <a href="javascript:;" class="hamburger-icon v2 visible-xs" data-toggle="layout-chat-open">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <!-- /toggle chat sidebar small screen-->
            </div>

            <ul class="nav navbar-nav hidden-xs">
                <li>
                    <!--<p class="navbar-text">-->
                    <!--Native Form Elements-->
                    <!--</p>-->
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-xs">
                <li>
                    <span class="navbar-text">
                        {% include 'version.html' %}
                    </span>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-xs">
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-user-o" aria-hidden="true"></i>
                        &nbsp;
                        <span id="nav-username">username: {{ user.username }}</span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'system_user:self_change_password' %}">Change Password</a></li>
                        <li><a id="top-logout" href="{% url 'authentications:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </header>
        <div class="main-content" style="background-color: white;">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}
{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js' %}"></script>
<script src="{% static 'scripts/ui/toggle.min.js' %}"></script>
<script src="{% static 'vendor/sweetalert/lib/sweet-alert.min.js' %}"></script>
<script src="{% static 'vendor/datatables/media/js/jquery.dataTables.min.js' %}"></script>
{% endblock %}
</body>

</html>

web_admin/templates/base_search_page.html
{% extends "base.html" %}
{% load static %}

{% block body_stylesheet %}
{{ block.super }}

<!--CSS for loading indicator-->
<style>
.loader {
    position: absolute;
    left: 50%;
    border: 6px solid #f3f3f3;
    border-radius: 50%;
    border-top: 6px solid #888;
    width: 48px;
    height: 48px;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
</style>
{% endblock %}

{% block content %}
{% endblock %}
{% block body_js %}
{{ block.super }}
    <script>
    function do_search(url, table_body_id, loader_indicator_id, search_result_notification_id, data) {
        var table_body = $("#" + table_body_id);
        var loader_indicator = $("#" + loader_indicator_id);
        table_body.empty();
        loader_indicator.show();
        $.ajax({
            url: url,
            type: "POST",
            data,
            dataType: "json",
            beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success: function (response) {
                loader_indicator.hide();
                if (response.status == true) {
                    table_body.append(response.table_content);
                    $("#" + search_result_notification_id).hide();
                } else {
                    $("#" + search_result_notification_id).show();
                }
            },
            error: function (err) {
                $("#" + search_result_notification_id).hide();
                loader_indicator.hide();
            }
        });
    }
</script>
{%  endblock %}

web_admin/templates/core.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title>Operation Web</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    {% block body_stylesheet %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/sweetalert/lib/sweet-alert.css' %}">
    <link rel="stylesheet" href="{% static 'styles/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'styles/urban.css' %}">
    <link rel="stylesheet" href="{% static 'styles/urban.skins.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}?{% now "U" %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}?{% now "U" %}">
    {% endblock %}
</head>

<body>
{% block body_content %}

<div class="app layout-fixed-header">

    <!--sidebar-panel-->
    {% include 'navigation.html' %}

    <!-- content panel -->
    <div class="main-panel">
        <!-- top header -->
        <header class="header navbar">

            <div class="brand visible-xs">
                <!-- toggle offscreen menu -->
                <div class="toggle-offscreen">
                    <a href="#" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <!-- /toggle offscreen menu -->
                <!-- logo -->
                <div class="brand-logo">
                    <!--<img src="images/logo-dark.png" height="15" alt="">-->
                </div>
                <!-- /logo -->
                <!-- toggle chat sidebar small screen-->
                <div class="toggle-chat">
                    <a href="javascript:;" class="hamburger-icon v2 visible-xs" data-toggle="layout-chat-open">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <!-- /toggle chat sidebar small screen-->
            </div>

            <ul class="nav navbar-nav hidden-xs">
                <li>
                    <!--<p class="navbar-text">-->
                    <!--Native Form Elements-->
                    <!--</p>-->
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-xs">
                <li>
                    <span class="navbar-text">
                        {% include 'version.html' %}
                    </span>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-xs">
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-user-o" aria-hidden="true"></i>
                        &nbsp;
                        <span id="nav-username">username: {{ user.username }}</span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'system_user:self_change_password' %}">Change Password</a></li>
                        <li><a id="top-logout" href="{% url 'authentications:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </header>
        <div class="main-content" style="background-color: white;">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}
{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js' %}"></script>
<script src="{% static 'scripts/ui/toggle.min.js' %}"></script>
<script src="{% static 'vendor/sweetalert/lib/sweet-alert.min.js' %}"></script>
<script src="{% static 'vendor/datatables/media/js/jquery.dataTables.min.js' %}"></script>
{% endblock %}
</body>

</html>

web_admin/templates/pagination_modal.html
{% if paginator.total_pages > 1 %}
<ul class="list-inline">
    <li><span>Page </span></li>
    {% if page_range.start > 1 %}
    <li><a class="page_idx">1</a></li>
    <li><span>...</span></li>
    {% endif %}

    {% for i in page_range %}
        {% if i == paginator.current_page %}
            <li><b><u><a>{{i}}</a></u></b></li>
        {% else %}
            <li><a class="page_idx">{{i}}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_range.stop < paginator.total_pages|add:1 %}
    <li><span>...</span></li>
    <li><a class="page_idx">{{ paginator.total_pages }}</a></li>
    {% endif %}
</ul>
<script>
    $(".page_idx").click(function() {
        $("#current_page_index").val($(this).text());
        searchUser('{% url 'payments:search_user' %}');
    });
</script>
{% endif %}

web_admin/templates/upload.html
{% extends "base.html" %}
{% load static %}
{% load permissions_filter %}
{% block body_stylesheet %}
{{ block.super }}
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="panel mb25">
    <div class="panel-heading">
        <h3>Upload and Download</h3>
    </div>
        <!--If success return green notification and return red notification if message is failed-->
    {% for msg in msgs.values %}
        {% if msg is not None %}
            <div class="col-xs-12">
                <div class="alert
                {% if "successfully" in msg %}
                    alert-success
                {% else %}
                    alert-danger
                {% endif %}
                alert-dismissable" id="msg-update-client">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    <strong>{{ msg }}</strong>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    <div class="panel-body">
        <div class="row no-margin">
            <div class="col-lg-6">
                    <form method="post" enctype="multipart/form-data" action="{% url 'upload:upload' %}">
                        {% csrf_token %}
                        <input type="file" name="file_data">
                        <button type="submit">Upload</button>
                    </form>
                    {% if uploaded_file_id %}
                        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
                    {% endif %}

            </div>
            <div class="col-lg-6">
                    <form method="post" action="{% url 'upload:download' %}">
                        {% csrf_token %}
                        <input type="text" name="file_id">
                        <button type="submit">Download</button>
                    </form>

            </div>

        </div>`
    </div>
</div>
{% endblock %}