web_admin/agent_type/urls.py
from .views.create import AgentTypeCreate
from .views.detail import DetailView
from .views.update import AgentTypeUpdateForm
from .views.delete import DeleteView
from .views.list import ListView

from django.contrib.auth.decorators import login_required
from django.conf.urls import url

app_name = 'agent_type'

urlpatterns = [
    url(r'^create/$', login_required(AgentTypeCreate.as_view(), login_url='authentications:login'), name="create-agent-type"),
    url(r'^list/$', login_required(ListView.as_view(), login_url='authentications:login'), name="agent-type-list"),
    url(r'^detail/(?P<agentTypeId>[0-9A-Za-z]+)/$', login_required(DetailView.as_view(), login_url='authentications:login'),
        name="agent-type-detail"),
    url(r'^delete/(?P<agent_type_id>[0-9A-Za-z]+)/$', login_required(DeleteView.as_view(), login_url='authentications:login'),
        name="agent-type-delete"),
    url(r'^(?P<agent_type_id>[0-9A-Za-z]+)/delete/$', login_required(DeleteView.as_view(), login_url='authentications:login'),
        name="delete-agent-type"),
    url(r'^update/(?P<agentTypeId>[0-9A-Za-z]+)/$', login_required(AgentTypeUpdateForm.as_view(), login_url='authentications:login'),
        name="agent-type-info"),
    url(r'^update-submit/(?P<agentTypeId>[0-9A-Za-z]+)/$',
        login_required(AgentTypeUpdateForm.as_view(), login_url='authentications:login'),
        name="agent-type-update"),
]

web_admin/bank/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from bank.views.bank.create import CreateView
from bank.views.bank.delete import DeleteView
from bank.views.bank.edit import EditView
from bank.views.bank.list import ListView
from bank.views.bank.detail import DetailsView


app_name = 'bank'

urlpatterns = [
    url(r'^management/$', login_required(ListView.as_view(), login_url='authentications:login'), name="bank_sofs_list"),
    url(r'^sofs/create/$', login_required(CreateView.as_view(), login_url='authentications:login'), name="bank_sofs_create"),
    url(r'^sofs/(?P<bank_id>[0-9A-Za-z]+)/edit/$', login_required(EditView.as_view(), login_url='authentications:login'), name="bank_sofs_edit"),
    url(r'^sofs/(?P<bank_id>[0-9A-Za-z]+)/detail/$', login_required(DetailsView.as_view(), login_url='authentications:login'), name="bank_sofs_detail"),
    url(r'^sofs/(?P<bank_id>[0-9A-Za-z]+)/delete/$', login_required(DeleteView.as_view(), login_url='authentications:login'), name="bank_sofs_delete"),
]

web_admin/bank_sofs/urls.py
from bank_sofs.views.sof.bank_sof_list import BankSOFView
from bank_sofs.views.sof.bank_sof_transaction import BankSOFTransaction

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from bank_sofs.views.sof.user_list import UserList

app_name = 'bank_sofs'

urlpatterns = [
    url(r'^sofs/$', login_required(BankSOFView.as_view(), login_url='authentications:login'), name="bank_sof"),
    url(r'^sofs/transaction/$', login_required(BankSOFTransaction.as_view(), login_url='authentications:login'), name="bank_sofs_transaction"),
    url(r'^users/$', login_required(UserList.as_view(), login_url='authentications:login'), name="search_user")
]

web_admin/web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.index, name="web-index"),
    url(r'^permission-denied', views.permission_denied, name="permission_denied"),
    url(r'^backlog$', views.backlog, name="backlog"),
]

web_admin/web_admin/urls.py
from django.conf.urls import include, url
from authentications.views.auth import logout_user
from web.views import health
from web.views import backlog

urlpatterns = [
    # url(r'^admin-portal/login/$', auth_views.login, {'template_name': 'authentications/login.html'}, name='login'),
    url(r'^admin-portal/', include('web.urls')),
    url(r'^admin-portal/authentications/', include('authentications.urls')),
    url(r'^admin-portal/clients/', include('clients.urls')),
    url(r'^admin-portal/password-center/', include('password_center.urls')),
    url(r'^admin-portal/balances/', include('balances.urls')),
    url(r'^admin-portal/health$', health, name="health"),
    url(r'^admin-portal/backlog/$', backlog, name="backlog"),
    url(r'^admin-portal/logout/$', logout_user, name='logout'),
    url(r'^admin-portal/agent-type/', include('agent_type.urls')),
    url(r'^admin-portal/system-user/', include('system_user.urls')),
    url(r'^admin-portal/service-group/', include('service_group.urls')),
    url(r'^admin-portal/services/', include('services.urls')),
    url(r'^admin-portal/agents/', include('agents.urls')),
    url(r'^admin-portal/customers/', include('customers.urls')),
    url(r'^admin-portal/cards/', include('cards.urls')),
    url(r'^admin-portal/card-type/', include('card_type.urls')),
    url(r'^admin-portal/cash/', include('cash_sofs.urls')),
    url(r'^admin-portal/payments/', include('payments.urls')),
    url(r'^admin-portal/api-management/', include('api_management.urls')),
    url(r'^admin-portal/centralize-configuration/', include('centralize_configuration.urls')),
    url(r'^admin-portal/bank-sof/', include('bank_sofs.urls')),
    url(r'^admin-portal/bank/', include('bank.urls')),
    url(r'^admin-portal/reconcile/', include('reconcile.urls')),
    url(r'^admin-portal/card-designs/', include('card_design.urls')),
    url(r'^admin-portal/card-provider/', include('card_provider.urls')),
    url(r'^admin-portal/card-sofs/', include('card_sofs.urls')),
    url(r'^admin-portal/balance-adjustment/', include('balance_adjustment.urls')),
    url(r'^admin-portal/campaign/', include('campaign.urls')),
    url(r'^admin-portal/fraud-prevention/', include('fraud_prevention.urls')),
    url(r'^admin-portal/rule-configuration/', include('rule_configuration.urls')),
    url(r'^admin-portal/voucher/', include('voucher.urls')),
    url(r'^admin-portal/report-configuration/', include('report_configuration.urls')),
    url(r'^admin-portal/category/', include('category.urls')),
    url(r'^admin-portal/product/', include('product.urls')),
    url(r'^admin-portal/shop-types/', include('shop_type.urls')),
    url(r'^admin-portal/shop-categories/', include('shop_category.urls')),
    url(r'^admin-portal/shops/', include('shop.urls')),
    url(r'^admin-portal/channel-gateway/services/', include('channel_gateway.service.urls')),
    url(r'^admin-portal/channel-gateway/apis/', include('channel_gateway.api.urls')),
    url(r'^admin-portal/uploads/', include('upload_management.urls')),
    url(r'^admin-portal/otp/', include('authentications.one_time_password_report.urls')),
    url(r'^admin-portal/trust-management/', include('trust_management.urls')),
]

web_admin/agent_type/views/create.py
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.restful_methods import RESTfulMethods
from web_admin.api_settings import AGENT_TYPE_CREATE_URL
from web_admin import setup_logger

from braces.views import GroupRequiredMixin

from django.conf import settings
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class AgentTypeCreate(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_CREATE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/create_agent_type.html"
    logger = logger

    permission_required = "auth.change_user"
    login_url = settings.LOGIN_URL
    raise_exception = False

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(AgentTypeCreate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Create Agent Type page ==========')
        context = super(AgentTypeCreate, self).get_context_data(**kwargs)
        self.logger.info('========== Finished showing Create Agent Type page ==========')
        return context

    def post(self, request, *args, **kwargs):
        self.logger.info('========== Start creating agent type ==========')
        params = {
            "name": request.POST.get('agent_type_input'),
            "description": request.POST.get('agent_type_description_input'),
        }

        data, success = self._post_method(api_path=AGENT_TYPE_CREATE_URL,
                                          func_description="Agent Type",
                                          logger=logger, params=params)
        if success:
            request.session['agent_type_create_msg'] = 'Added data successfully'
            self.logger.info('========== Finished creating agent type ==========')
            return redirect('agent_type:agent-type-list')
        else:
            context = {
                'agent_type_info': params,
                'error_msg': data
            }
            self.logger.info('========== Finished creating agent type ==========')
            return render(request, 'agent_type/create_agent_type.html', context)

web_admin/agent_type/views/delete.py
from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.restful_methods import RESTfulMethods
from web_admin.api_settings import AGENT_TYPE_DETAIL_URL, DELETE_AGENT_TYPE_URL
from web_admin import setup_logger
from django.shortcuts import render
from braces.views import GroupRequiredMixin

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
import logging

logger = logging.getLogger(__name__)


class DeleteView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_DELETE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_type_delete.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(DeleteView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Delete Agent Type page ==========')
        try:
            context = super(DeleteView, self).get_context_data(**kwargs)
            agent_type_id = context['agent_type_id']  
            self.logger.info('========== Finished showing Delete Agent Type page ==========')          
            return self._get_agent_type_detail(agent_type_id)
        except Exception as e:
            self.logger.error(e)
            context = {}
            self.logger.info('========== Finished showing Delete Agent Type page ==========')
            return context

    def post(self, request, *args, **kwargs):
        self.logger.info('========== Start deleting agent type ==========')
        agent_type_id = kwargs['agent_type_id']

        data, success = self._delete_method(api_path=DELETE_AGENT_TYPE_URL.format(agent_type_id),
                                            func_description="Delete agent type",
                                            logger=logger)
        if success:
            request.session['agent_type_delete_msg'] = 'Deleted data successfully'
            self.logger.info('========== Finished deleting agent type ==========')
            return HttpResponseRedirect(reverse('agent_type:agent-type-list'))
        else:
            context = self._get_agent_type_detail(agent_type_id)
            self.logger.info('========== Finished deleting agent type ==========')
            context.update({
                'msg':data,
            })
            return render(request, self.template_name, context)
        return success

    def _get_agent_type_detail(self, agent_type_id):
        param = {'id': agent_type_id}
        data, success = self._post_method(api_path=AGENT_TYPE_DETAIL_URL,
                                         func_description="Agent Type",
                                         logger=logger,
                                         params = param)
        return {'agent_type_info': data[0]}

web_admin/agent_type/views/detail.py
from braces.views import GroupRequiredMixin

from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.api_settings import AGENT_TYPE_DETAIL_URL
from web_admin.restful_methods import RESTfulMethods
from web_admin import setup_logger

from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class DetailView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_DELETE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_type_detail.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Agent Type Detail page ==========')
        context = super(DetailView, self).get_context_data(**kwargs)
        agent_type_id = context['agentTypeId']
        params = {"id": agent_type_id}
        data, success = self._post_method(AGENT_TYPE_DETAIL_URL, func_description="", logger=logger, params=params,
                                          only_return_data=True)
        if success:
            context = {
                'agent_type_info': data[0],
                'msg': self.request.session.pop('agent_type_update_msg', None)
            }
        else:
            context = {
                'agent_type_info': {},
                'msg': self.request.session.pop('agent_type_update_msg', None)
            }

        self.logger.info('========== Finished showing Agent Type Detail page ==========')
        return context

web_admin/agent_type/views/list.py
from braces.views import GroupRequiredMixin

from authentications.utils import get_correlation_id_from_username, check_permissions_by_user
from web_admin.api_settings import AGENT_TYPES_LIST_URL
from web_admin.restful_methods import RESTfulMethods
from web_admin import setup_logger

from django.views.generic.base import TemplateView

import logging

logger = logging.getLogger(__name__)


class ListView(GroupRequiredMixin, TemplateView, RESTfulMethods):
    group_required = "CAN_MANAGE_AGENT_TYPE"
    login_url = 'web:permission_denied'
    raise_exception = False

    def check_membership(self, permission):
        self.logger.info(
            "Checking permission for [{}] username with [{}] permission".format(self.request.user, permission))
        return check_permissions_by_user(self.request.user, permission[0])

    template_name = "agent_type/agent_types_list.html"
    logger = logger

    def dispatch(self, request, *args, **kwargs):
        correlation_id = get_correlation_id_from_username(self.request.user)
        self.logger = setup_logger(self.request, logger, correlation_id)
        return super(ListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start showing Agent Type List page ==========')
        data = self.get_agent_types_list()
        result = {
            'data': data,
            'msgs': {
                'del_msg': self.request.session.pop('agent_type_delete_msg', None),
                'cre_msg': self.request.session.pop('agent_type_create_msg', None)
            }
        }
        self.logger.info('========== Finished showing Agent Type List page ==========')
        return result

    def get_agent_types_list(self):
        data, success = self._post_method(api_path=AGENT_TYPES_LIST_URL,
                                         func_description="Agent Type List",
                                         logger=logger)
        return data

web_admin/bank_sofs/views/list.py
from django.views.generic.base import TemplateView
from web_admin.restful_methods import RESTfulMethods

import logging

logger = logging.getLogger(__name__)


class ListView(TemplateView, RESTfulMethods):
    template_name = "bank_sof/list.html"
    url = "report/v1/banks"

    def get_context_data(self, **kwargs):
        logger.info('========== Start get bank list ==========')
        data, success = self._get_method(self.url, "get bank list", logger, True)
        
        if success:
            logger.info('========== Finished get get bank list ==========')
            result = {'data': data}
            return result

web_admin/bank_sofs/templates/bank/create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="panel mb25">
    <div class="panel-heading border mb15">
        <h3>Create Bank Profile</h3>
    </div>
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
         <div class="col-xs-12">
                <div class="alert alert-danger alert-dismissable" id="msg-error">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    <strong>{{ message }}</strong>
                </div>
         </div>
        {% endif %}
    {% endfor %}

    <div class="panel-body">
        <div class="row no-margin">
            <div class="col-lg-12">
                <form id="submit-form" class="form-horizontal" role="form" method="post"
                      action="{% url 'bank_sofs:bank_sofs_create' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Is Active</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="bank_active" name="is_active" disabled>
                                <option value=1 {% if user_type_id == 1 %}selected="selected" {% endif %}>True
                                </option>
                                <option value=0 {% if user_type_id == 0 %}selected="selected" {% endif %}>False
                                </option>
                            </select>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Bank Name *</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="name"
                                   id="bank_name"
                                   value="{{ bank_info.name | default_if_none:'' }}" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">BIN</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="bin"
                                   id="bank_bin"
                                   value="{{ bank_info.bin | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Description</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="description"
                                   id="bank_description"
                                   value="{{ bank_info.description | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Credit Url</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="credit_url"
                                   id="bank_credit_url"
                                   value="{{ bank_info.credit_url | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Debit Url</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="debit_url"
                                   id="bank_debit_url"
                                   value="{{ bank_info.debit_url | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Check Status Url</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="check_status_url"
                                   id="check_status_url"
                                   value="{{ bank_info.check_status_url | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Cancel Url</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="cancel_url"
                                   id="txt_cancel_url"
                                   value="{{ bank_info.cancel_url | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Read Timeout (millisec.)</label>
                        <div class="col-sm-4">
                            <input type="number" class="form-control" id="txt_read_timeout" name="read_timeout" value="{{ bank_info.read_timeout }}" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Bank Account Number</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="account_number"
                                   id="bank_account_number"
                                   value="{{ bank_info.bank_account_number | default_if_none:'' }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Bank Account Name</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded" name="account_name"
                                   id="bank_account_name"
                                   value="{{ bank_info.bank_account_name | default_if_none:'' }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Currency</label>
                        <div class="col-sm-8">
                            <select class="form-control" id="bank_currency" name="currency" required>
                                {% for currency in currencies %}
                                {% if currency.0 == bank_info.currency %}
                                <option value="{{ currency.0 }}" selected>{{ currency.0 }}</option>
                                {% else %}
                                <option value="{{ currency.0 }}">{{ currency.0 }}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="pull-right">
                        <a href="{% url 'bank_sofs:bank_sofs_list' %}">
                                <input id="bank_btn_cancel" class="btn text-left mb15" type="button"
                                       value="Cancel"/>
                            </a>
                        <a href="{% url 'agent_type:create-agent-type' %}">
                            <input id="bank_btn_add" class="btn btn-success text-left mb15" type="submit"
                                   value="Add"/>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web_admin/bank_sofs/templates/bank/list.html
{% extends "base.html" %}
{% load static %}
{% load permissions_filter %}

{% block content %}
<div class="col-md-12">
    <div class="panel mb25">
        <div class="panel-heading border mb15">
            <h3>Bank List</h3>
        </div>
        {# {% if request.user|has_permission_name:"s"%} #}
        <div class="pull-right mr15 text-right">
            <a href="{% url 'bank_sofs:bank_sofs_create' %}">
                <input id="bank_sofs_btn_add" class="btn btn-success btn-block btn-sm mb15" type="button"
                       value="Add"/>
            </a>
        </div>
        {# {% endif %} #}

        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="col-xs-12">
                <div class="alert alert-success alert-dismissable" id="msg-update-client">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    <strong>{{ message }}</strong>
                </div>
            </div>
            {% endif %}
        {% endfor %}

        <div class="panel-body">
            <div class="no-more-tables">
                <table id='tbl_bank_sofs_list' class="table table-bordered table-striped mb0">
                    <thead>
                    <tr>
                        <th id="name">Bank Name</th>
                        <th id="account_name">Account Name</th>
                        <th id="account_number">Account Number</th>
                        <th id="currency">Currency</th>
                        <th id="is_active">Is Active</th>
                        <th id="created_date">Created Date</th>
                        <th id="modified_date">Modified Date</th>
                        <th class="col-sm-2" id="action">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bank in data %}
                    {% if bank.is_deleted == False %}
                        <tr>
                            <td>{{ bank.name|default_if_none:'' }}</td>
                            <td>{{ bank.bank_account_name|default_if_none:'' }}</td>
                            <td>{{ bank.bank_account_number|default_if_none:'' }}</td>
                            <td>{{ bank.currency|default_if_none:'' }}</td>
                            <td>{{ bank.is_active|yesno:'True,False' }}</td>
                            <td>{{ bank.created_timestamp|default_if_none:'' }}</td>
                            <td>{{ bank.last_updated_timestamp|default_if_none:'' }}</td>
                            <td class="col-sm-2">
                                    {% if permissions.is_permision_detail%}
                                        <a type="button"
                                            class="btn btn-outline btn-xs btn-info"
                                            role="button"
                                            id="bank_sof_btn_detail_{{ bank.id }}"
                                            href="{% url 'bank_sofs:bank_sofs_detail' bank.id %}">
                                            <span class="small">Detail</span>
                                        </a>
                                    {% endif %}
                                    {% if permissions.is_permision_edit%}
                                        <a type="button"
                                            class="btn btn-outline btn-xs btn-primary"
                                            role="button"
                                            href="{% url 'bank_sofs:bank_sofs_edit' bank.id %}"
                                            id="bank_sof_btn_edit_{{ bank.id }}">
                                            <span class="small">Edit</span>
                                        </a>
                                    {% endif %}
                                    {% if permissions.is_permision_delete%}
                                        <a type="button"
                                            class="btn btn-outline btn-xs btn-danger"
                                            role="button"
                                            href="{% url 'bank_sofs:bank_sofs_delete' bank.id %}"
                                            id="bank_sof_btn_delete_{{ bank.id }}">
                                            <span class="small">Delete</span>
                                        </a>
                                    {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}